decentraland/decentraland-dapps

README.md
package.json
src/lib/localStorage.spec.ts
src/lib/localStorage.ts
src/lib/types.ts
src/modules/storage/middleware.ts
src/modules/storage/reducer.ts
src/modules/storage/types.ts

close #10 
Add migrations for localstorage keys

BREAKING CHANGE: storage migration

---

package-lock.json
package.json
src/modules/transaction/sagas.ts

This PR changes the way we handle `replaced` transactions, so they are instead treated as dropped (marked as dropped in the state, and letting the saga find it's replacement).
This is better in the following ways: 
1. The saga can find the actual replacement transaction, and store its hash in the state, so we can show a proper link to the user
2. If the transaction is wrongly marked as replaced (due to a race condition or two unsynced nodes sitting behind a load balancer) instead of going to a final state (replaced) it will go to a polling state (dropped) which can fix the wrong state by finding a replacement transaction that matches the hash of the original transaction. If this happens the transaction is sent back to the pending transactions saga, that will ultimately change its status …

fix: wrong replaced tx

---

.circleci/config.yml

This PR removes the system dependencies on `libusb` since they are not required anymore by `decentraland-eth`. It also allow us to move to node 10.

chore: remove unsued dependencies

---

src/modules/transaction/actions.ts
src/modules/transaction/reducer.ts

This PR adds two synchronous actions to the `transaction` module:
```ts
clearTransactions(address: string, clearPendings: boolean = false)
```
Removes from the state all the transaction history for a given address. If the second param is set to `true` it also removes the pending transactions (default is `false`).
```ts
clearTransaction(hash: string)
```
Removes a single transaction from the state, by its tx hash.

feat: clear transactions

---

src/modules/transaction/reducer.ts

This PR fixes a bug that causes transactions to be repeated in the app state.
In some edge scenarios we dispatch `FETCH_TRANSACTION_REQUEST` actions of transactions that are already in the state:
1. When a transaction is dropped momentarily (ie the node responds `null` for it's status) and moments later comes back. In that scenario the transaction would be on the saga that watches dropped transactions and it would be sent back to the saga that watches pending transactions. This is where that happens: [LINK](https://github.com/decentraland/decentraland-dapps/blob/master/src/modules/transaction/sagas.ts#L160). That works fine at the saga level, but in the reducer a new transaction in "loading" or `null` status is inserted (which is good) because it will be picked up and updated by the …

fix: repeated transactions

---

src/modules/transaction/actions.ts
src/modules/transaction/sagas.ts

This PR adds a feature: watch reverted transactions for up to an hour and if the transaction is found to be confirmed, it updates its status.
This is because sometimes transactions are found to be reverted at first when they get mined (because they have a `blockNumber` in their tx status but no receipt). This happens more often in mainnet.
You can just install `decentraland-dapps@rc` in the marketplace repo, then run this code at the console to turn your confirmed transactions into reverted ones:
```js
const storage = JSON.parse(localStorage['decentraland-marketplace'])
storage.transaction.data.forEach(tx => {
if (tx.status === 'confirmed') {
tx.status = "reverted"
tx.timestamp = Date.now() - 1000
}
})
localStorage['decentraland-marketplace'] = JSON.stringify(storage)
```
Then go to …

feat: watch reverted transactions

---

src/modules/transaction/actions.ts
src/modules/transaction/reducer.ts
src/modules/transaction/sagas.ts

This PR fixes a bug that caused the failed transaction watcher to exit on transactions that have just failed. 
This is because by the time the `handleWatchRevertedTransaction` saga kicks in ([here](https://github.com/decentraland/decentraland-dapps/blob/master/src/modules/transaction/sagas.ts#L147)) the state has not been yet updated to mark the transaction as `reverted` ([there](https://github.com/decentraland/decentraland-dapps/blob/master/src/modules/transaction/sagas.ts#L152)). That caused the condition `txInState.status !== TRANSACTION_TYPES.reverted` inside the saga to always evaluate `true`, exiting the saga (so transactions marked as reverted erroneously would not be fixed).
They would still get fixed the next time the user returns to the dapp, because we pick the failed …

fix: failed transaction watcher

---

src/modules/wallet/sagas.ts
src/modules/wallet/types.ts
src/modules/wallet/utils.ts
src/providers/WalletProvider/WalletProvider.ts

Supports the new standard for Ethereum wallet permissions, where the URL must be approved before being able to access private information.
Release candidate: decentraland-dapps@3.7.0-rc2
Closes: https://github.com/decentraland/marketplace/issues/478 once https://github.com/decentraland/marketplace/pull/597 is merged
To test:
- Follow: https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8 to get the latest metamask version
- Go to the marketplace
- Checkout https://github.com/decentraland/marketplace/pull/597 if it's not merged
- Install the release candidate

feat: support approbable wallets

---

README.md
package-lock.json
package.json
src/containers/App/App.container.tsx
src/containers/App/App.tsx
src/containers/App/App.types.tsx
src/containers/App/index.ts
src/containers/Navbar/Navbar.container.tsx
src/containers/Navbar/Navbar.types.tsx
src/containers/index.ts
src/modules/location/actions.ts
src/modules/location/reducer.ts
src/modules/location/sagas.ts
src/modules/location/selectors.ts
src/modules/location/types.ts
src/modules/transaction/reducer.ts
src/modules/transaction/sagas.ts
src/modules/translation/defaults/ja.json
src/modules/wallet/sagas.ts
src/modules/wallet/types.ts
src/modules/wallet/utils.ts
tslint.json

This PR adds common functionality for the `location` module regarding the sign in page and the home page.
It also adds an `<App>` container that can be used to easily bootstrap an application that basically combines the `Navbar`, `Footer` and `Page` components.
I also updated the README with this new stuff and added missing documentation from previous releases.

feat: location

---

README.md
src/components/Intercom/index.ts
src/containers/EtherscanLink/EtherscanLink.container.ts
src/containers/Modal/Modal.container.ts
src/containers/Modal/Modal.tsx
src/containers/Modal/Modal.types.ts
src/containers/Modal/index.tsx
src/modules/modal/types.ts
src/providers/ModalProvider/ModalProvider.container.ts
src/providers/ModalProvider/ModalProvider.tsx
src/providers/ModalProvider/ModalProvider.types.ts

Modal features:
- Adhere more closely to the react lifecycle for modals. `componentWillUnmount` will fire when the modal closes
- Pass down a onClose prop to provider modals
Not sure the added complexity is worth it. We can keep only this commit: https://github.com/decentraland/decentraland-dapps/commit/7af6055206f531f3eeffd810539ed15c289c7e79 (which adds `componentWillUnmount`) if we want to remove it

feat: modal changes

---

package-lock.json
src/lib/localStorage.spec.ts
src/lib/localStorage.ts
src/modules/storage/middleware.ts

Make sure migrations still run in-memory when the LS quota is exceeded.
Fixes an issue in the Builder

fix: localstorage quota migration

---

.circleci/config.yml
package-lock.json
package.json
src/lib/api.ts
src/lib/utils.ts
src/modules/transaction/sagas.ts
src/modules/translation/utils.ts

BREAKING CHANGE: peer dependency redux-saga had a major updgrade
Some dependencies had major upgrades, like `typescript` and `axios`. I had to refactor a few utils to comply with typescript v3. I also fixed several vulnerabilities in the package-lock with an `npm audit fix`.
Since one peer dependency had a major upgrade, I labeled this commit as breaking, because it required action on the user's end in order to upgrade to the next version.
I made a release candidate to test it: `decentraland-dapps@5.0.0-rc`

chore: upgrade dependencies

---

src/modules/analytics/sagas.ts

eth_address is now a trait ,user_id is left blank
this is to standardize user_id on *.decentraland.org

Fix eth_address as trait

---

package.json
src/containers/SignInPage/SignInPage.container.ts
src/modules/wallet/actions.ts
src/modules/wallet/sagas.ts

**BREAKING CHANGE**: if not using the `WalletProvider` and `SignInPage` components, you may need to change your `connectWalletRequest` to a `enableWalletRequest`
The purpose of this PR is to remove the `ethereum.enable()` call from the `connectWalletRequest` saga. This is because currently our dapps try to connect to ethereum as soon as they boot, and if the domain has never been enabled before MetaMask will prompt the user with a popup to enable it, which is a very crappy experience. 
I created a separate action `enableWalletRequest` that performs the `ethereum.enable()` call and then if successful a `connectWalletRequest` action is triggered automatically.
So the usage now is basically the following:
1) Trigger a `connectWalletRequest` action when the dapp boots, if the website was …

feat: split enable and connect

---

README.md
src/modules/wallet/actions.ts
src/modules/wallet/reducer.ts
src/modules/wallet/sagas.ts
src/modules/wallet/utils.ts
src/providers/WalletProvider/WalletProvider.container.ts
src/providers/WalletProvider/WalletProvider.ts
src/providers/WalletProvider/WalletProvider.types.ts
src/providers/WalletProvider/utils.ts
src/providers/index.ts

This PR adds new functionality:
- New actions added: `CHANGE_ACCOUNT`, `CHANGE_NETWORK` and `DISCONNET_WALLET`
- `WalletProvider` dispatches `CHANGE_ACCOUNT` and `CHANGE_NETWORK` actions when a change is detected, so dApps can react to it.
- `disconnectWallet()` can be dispatched to go back to non-connected state.
Changes:
There are no breaking changes, although now it's not possible to set the `MANA_ADDRESS` from the outside. This renders `createWalletSaga` obsolete, but I left it with a deprecation warning encouraging users to import `walletSaga` directly instead.
This can be tested using the release candidate `decentraland-dapps@7.4.0-rc8`.
I deployed a version of the marketplace using this for easier manual testing here: https://public-930mdxzai.now.sh/

feat: handle network and account changes

---

src/containers/SignInPage/SignInPage.tsx
src/lib/eth.ts
src/lib/utils.ts
src/modules/transaction/sagas.ts
src/modules/transaction/txUtils.ts
src/modules/wallet/sagas.ts
src/modules/wallet/utils.ts
src/providers/WalletProvider/WalletProvider.ts
src/providers/WalletProvider/utils.ts

Removes the usage of `Eth.fromCurrentProvider()` (which uses `window.web3` under the hood). Also provides two new helpers: `getProvider(): Promise<EthereumProvider>` and `createEth(): Promise<Eth | null>` that can be used by dapps instead of using `window.ethereum` and `Eth.fromCurrentProvider()`. 
Currently `getProvider` just returns a promise that resolves to `window.ethereum`, but it's abstracted on its own helper so if we add more providers in the future (ie Formatic) the dapps don't need to worry about which provider to use, they just use the `getProvider` helper.
The `createEth` should be used as a replacement for `Eth.fromCurrentProvider()` on all the dapps, in order to comply with this migration: https://github.com/MetaMask/metamask-extension/issues/8077
For example, in our sagas …

fix: metamask migration

---

README.md
src/lib/eth.ts

Expose the provider connected with `dcl-connect`. It is not trivial for the user to import  `connection` from `decentraland-connect`.

feat: expose pristine provider

---

README.md
src/modules/authorization/sagas.ts
src/modules/authorization/types.ts
src/modules/translation/sagas.ts
src/modules/translation/types.ts

Added a `createAuthorizationSaga` function that accepts an optional configuration object `{ metaTransactionServerUrl?: string }` that allows to configure the `serverUrl` parameter of the `sendMetaTransaction` method used internally by the `authorization` module. The `authorizationSaga` is still exported with a non-configured meta transaction server. I figured is not needed for dapps that only run on Ethereum, but in case we want to make it mandatory to configure it we can remove that exported saga or replace it with a function that throws (that would require a major release instead of a minor one).

feat(Authorization): configure meta-tx server url

---

package-lock.json
package.json
src/modules/authorization/sagas.ts

I had to refactor the saga to use `ethers` instead of `web3x` because it didn't get along with the multicall provider. I didn't have to install `ethers` tho because it was already a dependency of other dependencies in the project.
I had to install also `@0xsequence/relayer` because otherwise the build would fail, although it's not explicitly imported in the code (it's an undocumented peer dependency of `@0xsequence/multicall`
I tested this as a release candidate `decentraland-dapps@12.10.0-rc7` installed in the marketplace using the production `.env` vars.

feat: use multicall for authorizations

---

package-lock.json
package.json
src/modules/profile/actions.spec.ts
src/modules/profile/actions.ts
src/modules/profile/reducer.spec.ts
src/modules/profile/reducer.ts
src/modules/profile/sagas.spec.ts
src/modules/profile/sagas.ts
src/tests/sagas.ts

This PR changes the way that the profile is updated after a description change in an avatar.
The idea of this change is to re-use the information we already have without the need of doing another request to the profile lambda endpoint.

fix: Avatar description update

---

.circleci/config.yml

This change makes the CI process:
- Save the `node_modules` directory once the test stage is done to later use the downloaded resources in the other stages.
- Load the `node_modules` directory from the cache in the build and release stages.
- Save the `dist` directory directory in the build stage.
- Load the `dist` directory in the release stage.

fix: Restore cache when needed

---

src/lib/localStorage.spec.ts
src/lib/localStorage.ts
src/lib/types.ts
src/modules/storage/middleware.ts

Fixes #183 
The first time an app using the storage middleware is loaded. The state will be stored with version 1 even if there are multiple migrations defined. This might bring issues because, for example: 
Imagine I have an app with 4 migrations. The first time I load the app and do thing on it, state will be stored with the current schema which is supposed to be version 4. However, it is tagged with version 1, causing the next session to try to execute migrations over up to date objects.

fix: Save the latest migration version when nothing is in storage

---

src/modules/authorization/utils.ts

Lowercase strings before comparing (this is because the contracts in `decentraland-transactions` are checksumed, but the ones in thegraph are lowercased)

fix(hasAuthorizations): lowercase contract addresses

---

src/lib/mana.spec.ts
src/lib/mana.ts

This PR fixes an issue with the `toFixedMANAValue` helper where trailing zeros would not be removed, allowing inputs to have more than the intended number of digits, ie:
- `9.500` nos is converted to `9.5`
- `9.000` now is converted to `9`

fix: toFixedMANAValue

---

src/lib/mana.spec.ts
src/lib/mana.ts

There were a few cases that I hadn't contemplated on my previous update 🤦 (#252). For instance, when formating an incomplete value, like `9.` that would be converted to `9`, and that would never allow a user to input a decimal value in an input that uses this helper on every update. 
For a max digits allowed of 2, with the previous update it worked like that:
- `9` -> `9` ✅ 
- `9.` -> `9` ❌ 
- `9.5` -> `9.5` ✅ 
- `9.50` -> `9.5` ❌ 
- `9.500` -> `9.5` ❌ 
- `9.5000` -> `9.5` ❌ 
Now it works like this: 
- `9` -> `9` ✅ 
- `9.` -> `9.` ✅ 
- `9.5` -> `9.5` ✅ 
- `9.50` -> `9.50` ✅ 
- `9.500` -> `9.50` ✅ 
- `9.5000` -> `9.50` ✅

fix: format mana again

---

src/modules/wallet/sagas.spec.ts
src/modules/wallet/sagas.ts
src/modules/wallet/utils.spec.ts
src/modules/wallet/utils.ts
src/tests/transactions.ts

We moved part of the chain switch logic used in the handleSwitchNetworkRequest sagas, so that we can use this utility within other projects such as explorer-website.

feat: move the logic from handleSwitchNetworkRequest sagas into utils

---

src/modules/analytics/snippet.ts
src/modules/analytics/utils.ts

This PR adds `user` to analytics methods to the stub, allowing to get the user `anonymousId` when the segment analytics lib is ready.

feat: Get segment anonymous user id

---

src/modules/features/reducer.spec.ts
src/modules/features/reducer.ts
src/modules/features/selectors.spec.ts
src/modules/features/selectors.ts

This PR adds two selectors to the feature flags module:
1. `isLoadingFeatureFlags` that retrieves if the feature flags are being loaded to avoid using the `getLoading` selector
2. `hasLoadedInitialFlags` that retrieves if the feature flags were loaded at least once.

feat: Add feature flags loading selectors

---

src/lib/peer.ts

As suggested [here](https://github.com/decentraland/decentraland-dapps/pull/324#discussion_r1060045835), this adds the `Pragma: no-cache` header.

feat: add no-cache header

---

src/containers/Navbar/Navbar.tsx
src/containers/Navbar/Navbar.types.tsx

This PR makes the "partially supported network modal" optional so we can choose to not show it if we need to change the user experience.

feat: Make partially supported network modal optional

---

src/modules/features/selectors.spec.ts
src/modules/features/selectors.ts
src/modules/features/types.ts
src/modules/wallet/sagas.ts

Changes:
- Add DAPPS app name to enum
- `StateWithFeatures` type has a possibly undefined features property. Clients might not be implementing the reducer so it might be possible that it is undefined. By typing it accordingly, we might be able to handle it right.
- `getState` now throws a `"'features' module not implemented"` error.
- `getIsFeatureEnabled` returns false if the provided app cannot be found in the state. There might be cases where the features are still loading and the app hasn't been added.

feat: DAPPS Application Name

---

src/lib/eth.ts
src/modules/transaction/actions.ts
src/modules/transaction/sagas.ts

This PR does the following:
- Updates the fetch transaction mechanism to use the `from` address in the request instead of the wallet's address which might differ after connecting with other wallet.
- Updates the `handleReplaceTransactionRequest` handler to get the network provided on each loop to prevent request to a Metamask provider that is not connected at the time.

fix: Dropped watched transaction error

---

src/containers/LoginModal/LoginModal.tsx
src/containers/LoginModal/LoginModal.types.ts
src/containers/SignInPage/SignInPage.container.ts
src/containers/SignInPage/SignInPage.types.ts

This PR adds a handler: `handleLoginConnect`, allowing a custom `onConnect` action in the component: `LoginModal` that fulfills each unique login flow in the dApps.

fix: Login Modal custom onConnect action

---

src/modules/transaction/sagas.ts

This PR fixes two call changes that were introduced in #396 that broke when being called due to lacking their context.

fix: Call effect without context

---

src/lib/BaseClient.spec.ts
src/lib/BaseClient.ts

This PR refactors the retrial mechanism in the `BaseClient`.
If the API will throw the same error every time the client makes the exactly same request, the `BaseClient` implementation should not try to repeat the failed request.

feat: Add non-retryable API errors mechanism for the BaseClient

---

src/modules/authorization/actions.spec.ts
src/modules/authorization/actions.ts
src/modules/authorization/reducer.spec.ts
src/modules/authorization/reducer.ts
src/modules/authorization/sagas.spec.ts
src/modules/authorization/sagas.ts
src/modules/authorization/selectors.spec.ts
src/modules/authorization/selectors.ts
src/modules/authorization/utils.ts

Add new actions and saga to handle the whole authorization flow
- Grant/Revoke token
- Wait for transaction to be confirmed
- Fetch authorizations
- Check that the authorization was done correctly

feat: add authorization flow saga

---

src/modules/authorization/reducer.ts

Do not reset authorizationError value when dispatching AUTHORIZATIONS_SUCCESS action

fix: authorization error reset on authorizations success

---

package-lock.json
package.json

This PR updates the Decentraland Connect version to allow Fortmatic to work in Goerli by using our own RPC.

fix: Update decentraland connect

---

src/modules/gateway/sagas.ts

Closes #428 
Related to this [PR](https://github.com/decentraland/decentraland-dapps/pull/427)

fix: Include Refunded as a final status when handling Set MANA Purchase

---

src/containers/withAuthorizedAction/withAuthorizedAction.types.ts

Make it possible to send partial values for translation even in nested objects:
Before this translationKeys object failed due to missing title
```
set_cap: {
description: "key
}
```
considering this english translation
```
set_cap: {
title: "Set cap title",
description: "Set cap description"
}
```

fix: make AuthorizationTranslationKeys optional recursively

---

src/containers/withAuthorizedAction/AuthorizationModal/AuthorizationModal.container.ts
src/containers/withAuthorizedAction/AuthorizationModal/AuthorizationModal.spec.tsx
src/containers/withAuthorizedAction/AuthorizationModal/AuthorizationModal.tsx
src/containers/withAuthorizedAction/AuthorizationModal/AuthorizationModal.types.ts
src/modules/authorization/actions.ts
src/modules/authorization/sagas.ts

Add new parameter `traceId` to all authorization flow events so that then a funnel can be created to analyze user behavior

feat: add trace id to authorization flow events

---

package-lock.json
package.json

This PR removes the unused `react-router` and `react-router-dom` dependencies.

fix: Remove unused router dependencies

---

src/containers/AssetCard/utils.tsx

This PR adds a blankspace between the listings wording.

fix: Blankspace in translation

---

src/lib/chainConfiguration.ts

The MANA Graph is not longer used for fetching balances or important information, we can deprecrate its usage.

feat: deprecate the manaGraphURL from the ChainConfiguration

---

README.md
package-lock.json
package.json
src/hooks/usePageTracking.ts
src/modules/analytics/sagas.ts

This PR is part of a series of PRs to stop using connected-react-router library. This PR starts sending the page event outside redux by using a hook when location changes
This is a breaking change as from now on we need to call `usePageTracking()` hooks in all our dapps

feat: add new page tracking hook

---

src/containers/withAuthorizedAction/AuthorizationModal/AuthorizationModal.spec.tsx
src/containers/withAuthorizedAction/AuthorizationModal/AuthorizationModal.tsx
src/containers/withAuthorizedAction/AuthorizationModal/utils.tsx
src/containers/withAuthorizedAction/withAuthorizedAction.tsx
src/containers/withAuthorizedAction/withAuthorizedAction.types.ts
src/modules/authorization/sagas.ts
src/modules/authorization/types.ts
src/modules/authorization/utils.ts
src/modules/translation/defaults/en.json
src/modules/translation/defaults/es.json
src/modules/translation/defaults/fr.json
src/modules/translation/defaults/ja.json
src/modules/translation/defaults/ko.json
src/modules/translation/defaults/zh.json

Add logic to be able to authorize minters through the authorization flow

feat: add mint authorization

---

package-lock.json
package.json
src/lib/marketplaceApi.ts
src/modules/gateway/sagas.spec.ts
src/modules/gateway/sagas.ts
src/modules/gateway/transak/Transak.spec.ts
src/modules/gateway/transak/Transak.ts
src/modules/gateway/transak/types.ts
src/modules/gateway/types.ts
src/types/transak.d.ts

Reverts decentraland/decentraland-dapps#643

Revert "Revert "Feat/transak bump""

---

src/lib/trades.spec.ts
src/lib/trades.ts

This PR changes the way we're building the trade object to be signed to correctly set the parameters of byte values (extra and the external check values). The issue seems to have come from the usage of ethers.utils.hexlify ethers.utils.toUtf8Bytes to allow building the trade signature without failures when the byte parameters where set as empty strings, which the signature function would not recognize as empty byte arrays (the real type).
This PR replaces the usage of those functions in favor of setting the value '0x', the empty bytes value, when the bytes parameters is empty or the set value when it's set.

fix: Remove bytes conversion

---

src/modules/features/selectors.spec.ts
src/modules/features/selectors.ts

Added a new `getFeatureVariant` selector function to retrieve feature variants from both environment variables and the Redux store.
- Added `getFeatureVariant` selector function that:
- First checks for variants defined in environment variables
- Falls back to store-defined variants if no environment override exists
- Returns `null` if no variant is found in either location
- Environment variants take precedence and are returned with a "Local variant" name
- Store variants are accessed using a composite key (`${app}-${feature}`)
- Added comprehensive test coverage for all scenarios:
- Environment-defined variants
- Store-defined variants
- Non-existent variants
- Cases where application features haven't been loaded yet
```typescript
const variant = getFeatureVariant(state, …
```

feat: Add feature variant selector

---

package-lock.json
package.json
src/containers/Banner/Banner.container.ts
src/containers/Banner/Banner.types.ts
src/containers/Banner/index.ts
src/modules/campaign/ContentfulClient.spec.ts
src/modules/campaign/ContentfulClient.ts
src/modules/campaign/actions.spec.ts
src/modules/campaign/actions.ts
src/modules/campaign/index.ts
src/modules/campaign/reducer.spec.ts
src/modules/campaign/reducer.ts
src/modules/campaign/sagas.spec.ts
src/modules/campaign/sagas.ts
src/modules/campaign/selectors.spec.ts
src/modules/campaign/selectors.ts
src/modules/campaign/types.ts
src/tests/contentfulMocks.ts

This PR adds the campaign module and the banner container.
The campaign module is in charge of communicating with Contentful to retrieve the admin entries which has linked banners and a campaign entity. It processes the localized information about those entries and stores it in the redux store.

feat: Add Campaign module and Banner component

---

package-lock.json
package.json
src/containers/Banner/Banner.container.ts
src/containers/Banner/Banner.tsx
src/containers/Banner/Banner.types.ts
src/lib/time.ts
src/modules/campaign/actions.ts
src/modules/campaign/sagas.spec.ts
src/modules/campaign/sagas.ts
src/modules/campaign/selectors.spec.ts
src/modules/campaign/selectors.ts
src/modules/campaign/types.ts

This PR adds tracking to the banner button. It sends as the id, the entry id, and as location, the identifier of the banner in the admin entity, which is practically the location of the banner (marketplaceHomepageBanner for example)

feat: Add tracking to banner button

---

src/containers/Banner/Banner.container.ts
src/containers/Banner/Banner.types.ts

This PR changes the way we're loading the banners to set the locale as the current site's locale.

fix: Use current locale for the banners

---

README.md
package-lock.json
package.json

BREAKING: Decentraland Connect now uses the OAuthV2 dependency.

BREAKING: Update the decentraland-connnect dependency to use Magic's OAuthV2

---

src/modules/wallet/sagas.spec.ts
src/modules/wallet/sagas.ts

This PR changes the `switchNetwork` action so it consider the wallet fetching process as part of the network switching. This is important because the fetching of the wallet is what builds the new wallet in the store with the balances and the current selected chain.
Without this change, in some cases, specially seen with Magic, switching networks results in the switching operation finishing before the store is updated.

fix: Network switching loader

---

src/containers/withAuthorizedAction/withAuthorizedAction.tsx
src/containers/withAuthorizedAction/withAuthorizedAction.types.ts

This PR changes the wallet prop for the authorizedWallet wallet, preventing a collision that can occur if the consumer of the withAuhtorizedAction passes the wallet prop to the component.

fix: Change wallet prop on withAuthorizedAction

---

src/containers/withAuthorizedAction/withAuthorizedAction.tsx
src/containers/withAuthorizedAction/withAuthorizedAction.types.ts
src/modules/analytics/utils.ts
src/modules/features/types.ts

This PR adds the manual mode to the magic auto sign in authorizations. This will be used to specifically set some actions to use the authorization UI.

feat: Add manual mode to magic auto sign in authorizations

---

package-lock.json
package.json
src/modules/campaign/ContentfulClient.spec.ts
src/modules/campaign/ContentfulClient.ts
src/tests/contentfulMocks.ts

This PR includes two fixes that make the campaign sagas work correctly:
- It changes the way we were building the entry with all locales to ignore the language when getting the value, as it does not come wrapped into a language, re-does the loop logic so we don't ignore fields that are set in the EN language but are set in other languages (not necessary but to make it a bit more generic) and includes the complete sys and metadata from the entry that will be used later to get if the entry is a banner.
- Changes the way we're fetching entries from fields to include the complete sys and metadata objects returned by `fetchEntryAllLocales`.

fix: Contentful client entry and entities fetching

---

package-lock.json
package.json
src/containers/Navbar/Navbar.types.tsx
src/containers/Navbar/Navbar2.container.tsx
src/containers/Navbar/Navbar2.tsx
src/modules/features/selectors.ts
src/modules/features/types.ts

This PR introduces a new feature flag (`launcherLinks`) that enables fetching dynamic launcher download links. These links will be used in the Navbar's "Download" button, allowing the client to update download targets without requiring code changes.

feat: Add feature flag to fetch dynamic launcher links for Navbar's Download button

---

src/modules/features/selectors.ts

This PR fixes the JSON parsing for the FF launcher-links variants

fix: Parsing FF JSON variant
