src/containers/EtherscanLink/EtherscanLink.container.ts, src/containers/EtherscanLink/EtherscanLink.tsx, src/containers/EtherscanLink/EtherscanLink.types.ts, src/containers/EtherscanLink/types.ts, src/containers/Navbar/Navbar.container.tsx, src/providers/TranslationProvider/TranslationProvider.container.ts, src/providers/TranslationProvider/TranslationProvider.tsx, src/providers/TranslationProvider/TranslationProvider.types.ts, src/providers/TranslationProvider/TranslationSetup/TranslationSetup.container.ts, src/providers/TranslationProvider/TranslationSetup/TranslationSetup.ts, src/providers/TranslationProvider/TranslationSetup/TranslationSetup.types.ts, src/providers/TranslationProvider/TranslationSetup/types.ts, src/providers/TranslationProvider/types.ts, src/providers/WalletProvider/WalletProvider.container.ts, src/providers/WalletProvider/WalletProvider.ts, src/providers/WalletProvider/WalletProvider.types.ts, src/providers/WalletProvider/types.ts, src/types.ts
=> feat: new standards

.circleci/config.yml, README.md, src/modules/transaction/sagas.ts, src/modules/transaction/types.ts, src/modules/transaction/utils.spec.ts, src/modules/transaction/utils.ts
- Add `buildTransactionWithReceiptPayload`
- Add circle
=> feat: add method buildTransactionWithReceiptPayload

.circleci/config.yml, package-lock.json, package.json
Closes #9 
I already added `GH_TOKEN` and `NPM_TOKEN` variables to the CI
=> ci: semantic-release

src/modules/wallet/utils.ts
`isApproved` sometimes hangs and never resolves or rejects the promise.
To mitigate this we'll use Promise.race, but we need `hasFinished` to avoid firing both functions.
`Promise.race` will *not* cancel the slower promise
=> fix: mitigate metamasks method `isApproved` hanging forever

README.md, package.json, src/containers/App/App.tsx, src/containers/EtherscanLink/index.ts, src/modules/modal/actions.ts, src/modules/modal/reducer.ts, src/modules/modal/selectors.ts, src/modules/modal/types.ts, src/providers/ModalProvider/ModalProvider.container.ts, src/providers/ModalProvider/ModalProvider.tsx, src/providers/ModalProvider/ModalProvider.types.ts, src/providers/ModalProvider/index.ts, src/providers/TranslationProvider/TranslationProvider.tsx, src/providers/TranslationProvider/TranslationProvider.types.ts, src/providers/TranslationProvider/TranslationSetup/index.ts, src/providers/TranslationProvider/index.ts, src/providers/WalletProvider/WalletProvider.types.ts, src/providers/WalletProvider/index.ts
TODO:
Related: https://github.com/decentraland/ui/pull/26
=> feat: add a modal provider

README.md, src/modules/modal/actions.ts, src/modules/modal/reducer.ts
Test on https://github.com/decentraland/builder/pull/162
Release candidate `3.12.0-rc`
=> feat: add toggleModal and allow for name typing

README.md, src/components/Intercom/Intercom.tsx, src/components/Intercom/Intercom.types.ts, src/components/Intercom/IntercomWidget.ts, src/components/Intercom/index.ts, src/components/index.ts, src/lib/utils.ts
This can be achieved without a component, by just exposing the helper class. TBD
RC: `3.13.0-rc6`
=> feat: add intercom component

src/modules/translation/utils.ts, src/providers/TranslationProvider/TranslationProvider.container.ts, src/providers/TranslationProvider/TranslationProvider.types.ts
=> fix: preferred locale

package-lock.json, package.json, src/containers/EtherscanLink/EtherscanLink.container.ts, src/containers/Footer/Footer.container.ts, src/containers/Modal/Modal.container.ts, src/containers/Modal/index.tsx, src/containers/Navbar/Navbar.container.tsx, src/containers/Navbar/Navbar.tsx, src/containers/SignInPage/SignInPage.container.ts, src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/fr.json, src/modules/translation/defaults/ja.json, src/modules/translation/defaults/ko.json, src/modules/translation/defaults/zh.json
Fixes typings, adds the new Navbar, and fixes the errors on `npm install`
=> feat: upgrade dependencies

package-lock.json, package.json, src/modules/storage/middleware.ts, src/modules/storage/types.ts
It needs to use T defined in `StorageMiddleware<T>`
=> fix: storage transform type

src/lib/api.ts
Instead of only configuring the response error, configure everything
=> feat: allow for fully configurable api response

package-lock.json, package.json, src/lib/eth.ts, src/modules/wallet/types.ts, src/modules/wallet/utils.ts
Depends on https://github.com/decentraland/decentraland-connect/pull/3
Please read the discussion about the API there!
=> feat: expose provider type

src/modules/wallet/utils.ts
=> fix: don't blow up on unsupported networks

package-lock.json, src/modules/wallet/actions.ts, src/modules/wallet/reducer.ts, src/modules/wallet/sagas.ts, src/modules/wallet/types.ts, src/modules/wallet/utils.ts, src/providers/WalletProvider/WalletProvider.ts, src/providers/WalletProvider/WalletProvider.types.ts
Also this PR removes the `balance` from `NetworkData` to avoid using Infura.
=> feat: refresh wallet balances

src/modules/authorization/utils.ts
Fix: Approval = (2^256) -1
This close #122
=> Fix: Approval = (2^256) -1

README.md, package-lock.json, package.json, src/containers/Navbar/Navbar.container.tsx, src/containers/Navbar/Navbar.tsx, src/containers/Navbar/Navbar.types.tsx, src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/fr.json, src/modules/translation/defaults/ja.json, src/modules/translation/defaults/ko.json, src/modules/translation/defaults/zh.json, src/providers/WalletProvider/WalletProvider.types.ts
Feat: Modal when the user is connected in a wrong network.
Closes #127
=> Feat: Modal when the user is connected in a wrong network.

README.md, src/modules/wallet/sagas.ts, src/modules/wallet/types.ts
=> feat: don't default chain id

package-lock.json, package.json
@cazala to fix the npm error and avoid --force
=> chore: bump react deps

src/modules/transaction/reducer.ts, src/modules/wallet/utils.ts
=> fix: lower-case addresses to avoid miss-matches

package-lock.json, package.json, src/containers/LoginModal/LoginModal.tsx, src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/zh.json
Depends on https://github.com/decentraland/ui/pull/111
Also fixes zh translations
Closes #156
=> feat: add a message for unsupported polygon wallets

src/containers/Navbar/Navbar.tsx, src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/fr.json, src/modules/translation/defaults/ja.json, src/modules/translation/defaults/ko.json, src/modules/translation/defaults/zh.json
Show a different copy when we don't have a display name for the connected network
=> feat: handle unknown networks

src/containers/AddressProvider/AddressProvider.container.tsx, src/containers/AddressProvider/AddressProvider.tsx, src/containers/AddressProvider/AddressProvider.types.ts, src/containers/AddressProvider/index.ts, src/containers/AddressProvider/utils.ts, src/modules/wallet/actions.ts, src/modules/wallet/reducer.ts, src/modules/wallet/sagas.ts, src/modules/wallet/selectors.ts
Adds the logic to get the address if a ENS one is provided in the URL.
=> feat: Add AddressProvider component

package-lock.json, package.json, src/modules/toast/toasts/meta-transactions.tsx
add docs link and upgrade dcl-ui
=> feat: add docs link

src/lib/entities.ts, src/modules/profile/actions.spec.ts, src/modules/profile/actions.ts, src/modules/profile/reducer.spec.ts, src/modules/profile/reducer.ts, src/modules/profile/sagas.spec.ts, src/modules/profile/sagas.ts, src/modules/profile/selectors.spec.ts, src/modules/profile/selectors.ts
This PR adds a new action to change the profile alias.
=> feat: Add action to set the profile alias

package-lock.json, package.json, src/lib/chainConfiguration.ts
Bumps https://github.com/decentraland/common-schemas to 4.6.0
=> feat: update common schemas

src/modules/transaction/utils.spec.ts, src/modules/transaction/utils.ts
This PR adds a helper to wait for transactions to be completed using the the transaction's state.
=> feat: Add wait for tx

package-lock.json, package.json, src/lib/api.spec.ts, src/lib/api.ts
add retry mechanism to baseapi
=> feat: add retry mechanism to baseapi

src/modules/transaction/utils.spec.ts, src/modules/transaction/utils.ts
This PR follows adds to the `waitForTx` util the functionality to wait for dropped transactions that get a different treatment in [the sagas](https://github.com/decentraland/decentraland-dapps/blob/master/src/modules/transaction/sagas.ts).
=> fix: Wait for dropped transactions to be completed

package-lock.json, package.json, src/modules/toast/actions.ts, src/modules/toast/cache.ts, src/modules/toast/sagas.ts, src/modules/toast/types.ts, src/providers/ToastProvider/ToastProvider.tsx
This PR allows setting a position for toasts.
Depends on: https://github.com/decentraland/ui/pull/233
=> feat: Allow set position for toasts

package-lock.json, package.json, src/providers/ToastProvider/ToastProvider.tsx
This PR allows sending the property `className` to the toast component.
=> feat: Send the property className to the Toast component

src/modules/manaFiatGateway/transak/Transak.ts
=> fix: After closing Transak modal remove external added css prop

src/lib/entities.ts, src/modules/profile/sagas.spec.ts, src/modules/profile/sagas.ts, src/modules/profile/utils.spec.ts, src/modules/profile/utils.ts, src/tests/profileMocks.ts
=> feat: use profile fetched from profile lambda instead of profile entity from catalyst client

src/lib/peer.spec.ts, src/lib/peer.ts, src/lib/types.ts, src/modules/profile/sagas.spec.ts, src/modules/profile/sagas.ts
=> feat: add a flag to bypass profile cache

src/containers/BuyManaWithFiatModal/BuyManaWithFiatFeedbackModal/BuyManaWithFiatFeedbackModal.tsx, src/containers/BuyManaWithFiatModal/BuyManaWithFiatFeedbackModal/BuyManaWithFiatFeedbackModal.types.ts, src/modules/manaFiatGateway/sagas.spec.ts, src/modules/manaFiatGateway/sagas.ts, src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/zh.json
=> feat: Show in which network you bought MANA in the success modal

package-lock.json, package.json, src/containers/BuyManaWithFiatModal/BuyManaWithFiatFeedbackModal/BuyManaWithFiatFeedbackModal.container.ts, src/containers/BuyManaWithFiatModal/BuyManaWithFiatFeedbackModal/BuyManaWithFiatFeedbackModal.tsx, src/containers/BuyManaWithFiatModal/BuyManaWithFiatFeedbackModal/BuyManaWithFiatFeedbackModal.types.ts, src/containers/BuyManaWithFiatModal/BuyManaWithFiatFeedbackModal/index.ts, src/containers/BuyManaWithFiatModal/BuyManaWithFiatModal.container.ts, src/containers/BuyManaWithFiatModal/BuyManaWithFiatModal.tsx, src/containers/BuyManaWithFiatModal/BuyManaWithFiatModal.types.ts, src/modules/location/sagas.spec.ts, src/modules/location/sagas.ts, src/modules/manaFiatGateway/actions.spec.ts, src/modules/manaFiatGateway/actions.ts, src/modules/manaFiatGateway/moonpay/MoonPay.ts, src/modules/manaFiatGateway/reducer.spec.ts, src/modules/manaFiatGateway/reducer.ts, src/modules/manaFiatGateway/sagas.spec.ts, src/modules/manaFiatGateway/sagas.ts, src/modules/manaFiatGateway/selectors.spec.ts, src/modules/manaFiatGateway/selectors.ts, src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/zh.json
=> feat: Add in-progress and failure states to the Buy MANA flow

src/modules/storage/middleware.ts
=> feat: Store purchases on local storage

src/lib/entities.ts, src/lib/peer.ts, src/modules/profile/sagas.spec.ts, src/modules/profile/sagas.ts, src/modules/profile/utils.ts
=> feat: add "hashesByKey" when building profile entity before deploying it

src/modules/mana/actions.spec.ts, src/modules/mana/actions.ts, src/modules/manaFiatGateway/reducer.spec.ts, src/modules/manaFiatGateway/reducer.ts, src/modules/manaFiatGateway/sagas.spec.ts, src/modules/manaFiatGateway/sagas.ts
=> fix: mana purchases pending forever

src/modules/manaFiatGateway/sagas.spec.ts, src/modules/manaFiatGateway/sagas.ts, src/modules/manaFiatGateway/transak/Transak.spec.ts, src/modules/manaFiatGateway/transak/Transak.ts, src/modules/manaFiatGateway/transak/types.ts
Related to https://github.com/decentraland/marketplace/pull/1322
=> feat: Extend Transak Class for NFTs supporting

package-lock.json, package.json, src/containers/AddressProvider/AddressProvider.tsx, src/containers/AddressProvider/utils.ts, src/containers/LoginModal/LoginModal.tsx, src/lib/entities.ts, src/lib/eth.ts, src/modules/authorization/sagas.ts, src/modules/authorization/utils.ts, src/modules/transaction/sagas.ts, src/modules/transaction/txUtils.ts, src/modules/transaction/types.ts, src/modules/wallet/sagas.spec.ts, src/modules/wallet/sagas.ts, src/modules/wallet/utils.spec.ts, src/modules/wallet/utils/buildWallet.ts, src/modules/wallet/utils/fetchManaBalance.ts, src/modules/wallet/utils/getAddEthereumChainParameters.ts, src/modules/wallet/utils/getProviderChainId.ts, src/modules/wallet/utils/getTargetNetworkProvider.ts, src/modules/wallet/utils/switchProviderChainId.ts, src/providers/WalletProvider/WalletProvider.types.ts
Reverts decentraland/decentraland-dapps#347
=> fix: Revert ether import changes

README.md
Signed-off-by: Fernando Zavalia <24811313+fzavalia@users.noreply.github.com>
=> fix: Trigger patch release

src/modules/gateway/transak/Transak.ts, src/modules/gateway/transak/types.ts
=> feat: Close Transak widget on Back to App click

src/modules/gateway/actions.spec.ts, src/modules/gateway/actions.ts, src/modules/gateway/moonpay/MoonPay.spec.ts, src/modules/gateway/moonpay/MoonPay.ts, src/modules/gateway/moonpay/types.ts, src/modules/gateway/reducer.spec.ts, src/modules/gateway/reducer.ts, src/modules/gateway/sagas.spec.ts, src/modules/gateway/sagas.ts, src/modules/gateway/selectors.spec.ts, src/modules/gateway/selectors.ts, src/modules/gateway/transak/Transak.spec.ts, src/modules/gateway/transak/Transak.ts, src/modules/gateway/transak/types.ts, src/modules/gateway/types.ts, src/modules/gateway/utils.ts, src/modules/transaction/sagas.ts
=> feat: Recover Transak order status with polling

package-lock.json, package.json
This PR updates the decentraland-transactions package version
=> feat: Upgrade decentraland-transactions version

package-lock.json, package.json, src/containers/BuyManaWithFiatModal/BuyManaWithFiatFeedbackModal/BuyManaWithFiatFeedbackModal.tsx, src/containers/Navbar/Navbar.tsx, src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/fr.json, src/modules/translation/defaults/ja.json, src/modules/translation/defaults/ko.json, src/modules/translation/defaults/zh.json
This PR updates the dapps navbar submenu and translations
=> feat: Add dapps submenu

package-lock.json, package.json, src/containers/Navbar/Navbar.tsx, src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/fr.json, src/modules/translation/defaults/ja.json, src/modules/translation/defaults/ko.json, src/modules/translation/defaults/zh.json
This PR updates the `decentraland-ui` lib version, getting the latest navbar version with the `DAO`'s submenu.
=> feat: Update navbar submenu

src/lib/api.spec.ts, src/lib/api.ts, src/lib/localStorage.spec.ts
This PR enables retries on demand for custom requests.
=> feat: Add retry on demand for requests

.github/workflows/audit.yml
Test failures related to [this issue](https://github.com/nodejs/node/issues/47563).
=> chore: Add audit workflow

package-lock.json, package.json
=> feat: Update transactions lib to 1.44.0

package-lock.json, package.json
This PR upgrades decentraland-ui lib
=> feat: Upgrade decentraland-ui

package.json, src/modules/gateway/moonpay/MoonPay.spec.ts, src/modules/wallet/actions.spec.ts, src/modules/wallet/reducer.spec.ts, src/modules/wallet/reducer.ts, src/modules/wallet/sagas.spec.ts, src/modules/wallet/sagas.ts, src/modules/wallet/selectors.spec.ts, src/tests/setupTests.ts
Related to https://github.com/decentraland/marketplace/issues/1619
=> refactor: Clean state when fails enabling/connecting wallet without dispatching disconnectWallet

package-lock.json, package.json, src/containers/Navbar/Navbar.tsx
This PR tracks when a user clicks a navbar menu or submenu option.
Depends on: https://github.com/decentraland/ui/pull/351
Closes #424
=> feat: Track navbar menu clicks

package-lock.json, package.json
This PR upgrades the decentraland-ui package
=> chore: Update decentraland-ui package

src/containers/withAuthorizedAction/AuthorizationModal/AuthorizationModal.spec.tsx, src/containers/withAuthorizedAction/AuthorizationModal/AuthorizationModal.tsx, src/modules/authorization/sagas.spec.ts, src/modules/authorization/sagas.ts
Add tracking events for authorization flow
=> feat: track events authorization flow

src/containers/withAuthorizedAction/AuthorizationModal/AuthorizationModal.tsx, src/containers/withAuthorizedAction/AuthorizationModal/AuthorizationModal.types.ts, src/containers/withAuthorizedAction/AuthorizationModal/utils.tsx, src/containers/withAuthorizedAction/withAuthorizedAction.tsx, src/containers/withAuthorizedAction/withAuthorizedAction.types.ts, src/modules/translation/defaults/en.json
Add some changes to authorization modal component to support authorization approval for NFTs in marketplace
=> feat: add authorization approval changes

package-lock.json, package.json, src/containers/Navbar/Navbar.tsx, src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/fr.json, src/modules/translation/defaults/ja.json, src/modules/translation/defaults/ko.json, src/modules/translation/defaults/zh.json
This PR upgrades the decentraland-ui package
=> feat: Upgrade decentraland-ui package

README.md
=> feat: Insignificant change

package-lock.json, package.json
Bump common schemas version to add new hands wear category
=> feat: bump common schemas version

package-lock.json, package.json, src/lib/entities.ts
this PR: 
- bump catalyst client
- improve code
=> fix: bump catalyst client 

package-lock.json, package.json, src/lib/chainConfiguration.ts
=> feat: add sepolia link

src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/fr.json, src/modules/translation/defaults/ja.json, src/modules/translation/defaults/ko.json, src/modules/translation/defaults/zh.json
This PR adds the default translations for the places navbar options
=> feat: Add places navbar translations

src/lib/error.ts
This PR add the widely used `isErrorWithMessage` and `isAPIError` that are used all through our dApps.
=> feat: Add error functions

package-lock.json, package.json, src/containers/UserMenu/UserMenu.tsx, src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/fr.json, src/modules/translation/defaults/ja.json, src/modules/translation/defaults/ko.json, src/modules/translation/defaults/zh.json
This PR updates the UserMenu option from UI.
Depends on: https://github.com/decentraland/ui/pull/393
Closes [#decentraland/profile/77](https://github.com/decentraland/profile/issues/77)
=> feat: Update navbar UserMenu

jest.config.js, package-lock.json, package.json
Breaks tests due to the new ESM module.
=> feat: Update decentraland connect

package-lock.json, package.json
This PR updates decentraland connect to its latest version, changing it from ESM to CommonJS and updating the wallet connect packages.
=> fix: Update decentraland connect

package-lock.json, package.json
This PR updates the UI package.
=> fix: Update UI

package-lock.json, package.json
This reverts commit c9d553b5b0b84b62d610cec125e9aec109dffbab.
=> Revert "fix: updated decentrland ui"

src/modules/features/types.ts
This PR adds the profile element to the ApplicationName enum.
=> feat: Add profile ApplicationName

package-lock.json, package.json
=> feat: update decentralnd ui

package-lock.json, package.json, src/components/RarityFilter/RarityFilter.tsx, src/components/RarityFilter/RarityFilter.types.ts, src/components/RarityFilter/index.ts, src/components/index.ts, src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/fr.json, src/modules/translation/defaults/ja.json, src/modules/translation/defaults/ko.json, src/modules/translation/defaults/zh.json
This PR adds the RarityFilter component so it can be used in both the Profile site and the Marketplace.
=> feat: Add RarityFilter

src/containers/AssetStatusFilter/AssetStatusFilter.tsx
This PR fixes the translations in the asset status filter component.
=> fix: Asset status filter translations

package-lock.json, package.json, src/containers/UserInformation/UserInformation.container.ts, src/containers/UserInformation/UserInformation.tsx, src/containers/UserInformation/UserInformation.types.ts
This PR augments the `UserInformation` component to track each action.
=> feat: Add tracking to the UserInformation component

package-lock.json, package.json, src/containers/UserInformation/UserInformation.tsx
This PR uses the new tracking logic from the updated component in the UI.
=> fix: Use new tracking logic

src/containers/UserInformation/UserInformation.tsx
This PR changes the returning type of the tracking method and adds the analytics object to the `useCallback` functions.
=> fix: UserInformation tracking

package-lock.json, package.json
This PR updates `decentraland-ui` to it's latest version so we can correctly track the `UserInformation` component actions.
=> fix: Update decentraland-ui

package-lock.json, package.json, src/containers/UserInformation/UserInformation.container.ts
This PR does two things:
- Fixes the UserInformation container so it works without transactions.
- Reverts a dependency upgrade that broke the fetching of profiles.
=> fix: UserInformation should work without transactions

src/containers/UserInformation/UserInformation.tsx, src/containers/UserInformation/constants.ts, src/containers/UserInformation/index.ts
This PR adds events constants so they can be used in other projects.
=> fix: Add UserInformation events constants

package-lock.json, package.json
This PR updates the DCL UI dependency to fix the `Profile` component not showing the hashtag on unclaimed names.
=> fix: Update DCL UI

package-lock.json, package.json
=> fix: update ui dependency

src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/fr.json, src/modules/translation/defaults/ja.json, src/modules/translation/defaults/ko.json, src/modules/translation/defaults/zh.json
This PR adds the missing translation for the DAO grants submenu.
=> fix: DAO grants submenu

package-lock.json, package.json
Upgrade decentraland connect version to allow MAGIC as a provider
=> feat: update decentraland connect version

src/containers/Navbar2/Navbar2.container.tsx, src/containers/Navbar2/Navbar2.types.tsx
This PR adds the avatar info into the navbar2
=> fix: Add avatar info into the navbar

src/containers/Navbar2/Navbar2.container.tsx, src/containers/Navbar2/Navbar2.tsx, src/containers/Navbar2/Navbar2.types.tsx
Fix navbar2 notifications locale
=> fix: Navbar2 notifications locale

package-lock.json, package.json, src/components/AddressField/AddressField.tsx, src/components/AddressField/index.ts, src/components/AddressField/utils.ts
Add AddressField component with resolveAddress function
=> feat: add address field

src/components/AddressField/utils.ts
Add tracking event for resolve address
=> feat: track resolve address

package-lock.json, package.json, src/containers/Footer/Footer.tsx, src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/fr.json, src/modules/translation/defaults/ja.json, src/modules/translation/defaults/ko.json, src/modules/translation/defaults/zh.json
Update decentraland-ui dependency
=> feat: update decentraland ui

src/modules/gateway/sagas.ts, src/modules/gateway/types.ts
For the builder I only need wert, so having to define transak and moon pay is unnecessary.
This PR makes it possible to define only the desired gateways.
=> fix: Make gateways optional

package-lock.json, package.json
This PR upgrades the package `@dcl/schemas` to the version `11.5.0`
=> feat: Upgrade @dcl/schemas

src/lib/peer.spec.ts, src/lib/peer.ts, src/modules/profile/actions.spec.ts, src/modules/profile/actions.ts, src/modules/profile/reducer.spec.ts, src/modules/profile/reducer.ts, src/modules/profile/sagas.spec.ts, src/modules/profile/sagas.ts, src/modules/profile/selectors.spec.ts, src/modules/profile/selectors.ts
This PR adds the functionality to load multiple profiles at the same time and the selectors that can be used for this case.
=> feat: Add loading multiple profiles functionality

package-lock.json, package.json, src/lib/marketplaceApi.ts, src/modules/gateway/sagas.spec.ts, src/modules/gateway/sagas.ts, src/modules/gateway/transak/Transak.spec.ts, src/modules/gateway/transak/Transak.ts, src/modules/gateway/transak/types.ts, src/modules/gateway/types.ts, src/types/transak.d.ts
Reverts decentraland/decentraland-dapps#639
=> Revert "Feat/transak bump"

src/modules/gateway/sagas.ts, src/modules/gateway/transak/Transak.spec.ts, src/modules/gateway/types.ts
Reverts decentraland/decentraland-dapps#646
=> Revert "feat: remove marketplace api url var from Transak since its already t…"

package-lock.json, package.json, src/lib/marketplaceApi.ts, src/modules/gateway/sagas.spec.ts, src/modules/gateway/sagas.ts, src/modules/gateway/transak/Transak.spec.ts, src/modules/gateway/transak/Transak.ts, src/modules/gateway/transak/types.ts, src/modules/gateway/types.ts, src/types/transak.d.ts
Reverts decentraland/decentraland-dapps#645
=> Revert "Revert "Revert "Feat/transak bump"""

package-lock.json, package.json
This PR updates the decentraland-transaction dependency to fix an issue with the Axelar calls.
=> fix: Transactions update

src/containers/withAuthorizedAction/withAuthorizedAction.tsx, src/containers/withAuthorizedAction/withAuthorizedAction.types.ts
This PR fixes the incorrect propagation of new props down to the components being authorized.
=> fix: Incorrect withAuthorizedAction props propagation

src/containers/Web2TransactionModal/Web2TransactionsModal.tsx, src/modules/translation/defaults/en.json, src/modules/translation/defaults/es.json, src/modules/translation/defaults/fr.json, src/modules/translation/defaults/ja.json, src/modules/translation/defaults/ko.json, src/modules/translation/defaults/zh.json
This PR adds internationalization to the `Web2TransactionsModal`.
=> feat: Add internationalisation to modal

README.md, src/modules/credits/CreditsClient.ts, src/modules/credits/actions.ts, src/modules/credits/sagas.spec.ts, src/modules/credits/sagas.ts, src/modules/features/selectors.ts
=> feat: use credits SSE endpoint

package-lock.json, package.json, src/lib/marketplaceApi.ts, src/modules/gateway/sagas.spec.ts, src/modules/gateway/sagas.ts, src/modules/gateway/types.ts
Use the session id besides the signature to init Wert's widget.
=> feat: Init Wert widget with the session id

src/modules/analytics/types.ts, src/modules/analytics/utils.ts
Automatically detects and includes wallet information in all analytics events.
**Changes:**
- Added wallet detection for EVM (MetaMask, Rabby, Coinbase) and Solana (Phantom, Sollet, Brave, etc.) wallets
- Implemented Segment middleware to enrich all tracking events with wallet context
=> feat: add wallet into tracking context
